apiVersion: v1
kind: Service
metadata:
  name: phonebook-service
  labels:
    app: phonebook-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    app: phonebook-app
