apiVersion: apps/v1
kind: Deployment
metadata:
  name: phonebook-app-deployment
  labels:
    app: phonebook-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phonebook-app
  template:
    metadata:
      labels:
        app: phonebook-app
    spec:
      containers:
      - name: phonebook-app
        image: Kartik/phonebook-main
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-admin-password
        envFrom:
        - configMapRef:
            name: servers-configmap
