apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    app: mysql
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
