apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    app: result-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
  selector:
    app: result-app
